# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.1"
manifest_format = "2.0"
project_hash = "d2a4aa26a75f55beed4f2df9bb7d856d7e753b25"

[[deps.ProlateSpheroidal]]
path = "."
uuid = "bc375c4d-1d06-41b0-a1fb-6f2d8a7a2632"
version = "1.0.0-DEV"
